/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KlasemenRouteImport } from './routes/klasemen'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as PemainRouteImport } from './routes/pemain'
import { Route as PutraRouteImport } from './routes/putra'
import { Route as PutriRouteImport } from './routes/putri'
import { Route as TimRouteImport } from './routes/tim'
import { Route as TopSkorRouteImport } from './routes/top-skor'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContingentsRouteImport } from './routes/admin.contingents'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminMatchOfficialsRouteImport } from './routes/admin.match-officials'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminOfficialsRouteImport } from './routes/admin.officials'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as PertandinganMatchIdRouteImport } from './routes/pertandingan.$matchId'
import { Route as TimTeamIdRouteImport } from './routes/tim.$teamId'
import { Route as MatchMatchIdControlRouteImport } from './routes/match.$matchId.control'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasemenRoute = KlasemenRouteImport.update({
  id: '/klasemen',
  path: '/klasemen',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const PemainRoute = PemainRouteImport.update({
  id: '/pemain',
  path: '/pemain',
  getParentRoute: () => rootRouteImport,
} as any)
const PutraRoute = PutraRouteImport.update({
  id: '/putra',
  path: '/putra',
  getParentRoute: () => rootRouteImport,
} as any)
const PutriRoute = PutriRouteImport.update({
  id: '/putri',
  path: '/putri',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const TopSkorRoute = TopSkorRouteImport.update({
  id: '/top-skor',
  path: '/top-skor',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContingentsRoute = AdminContingentsRouteImport.update({
  id: '/contingents',
  path: '/contingents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchOfficialsRoute = AdminMatchOfficialsRouteImport.update({
  id: '/match-officials',
  path: '/match-officials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficialsRoute = AdminOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const PertandinganMatchIdRoute = PertandinganMatchIdRouteImport.update({
  id: '/pertandingan/$matchId',
  path: '/pertandingan/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimTeamIdRoute = TimTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TimRoute,
} as any)
const MatchMatchIdControlRoute = MatchMatchIdControlRouteImport.update({
  id: '/match/$matchId/control',
  path: '/match/$matchId/control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/live': typeof LiveRoute
  '/masuk': typeof MasukRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/admin/contingents': typeof AdminContingentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/match-officials': typeof AdminMatchOfficialsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/pertandingan/$matchId': typeof PertandinganMatchIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/match/$matchId/control': typeof MatchMatchIdControlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/live': typeof LiveRoute
  '/masuk': typeof MasukRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/admin/contingents': typeof AdminContingentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/match-officials': typeof AdminMatchOfficialsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/pertandingan/$matchId': typeof PertandinganMatchIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/match/$matchId/control': typeof MatchMatchIdControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/live': typeof LiveRoute
  '/masuk': typeof MasukRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/admin/contingents': typeof AdminContingentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/match-officials': typeof AdminMatchOfficialsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/pertandingan/$matchId': typeof PertandinganMatchIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/match/$matchId/control': typeof MatchMatchIdControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/live'
    | '/masuk'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/admin/contingents'
    | '/admin/groups'
    | '/admin/match-officials'
    | '/admin/matches'
    | '/admin/officials'
    | '/admin/players'
    | '/admin/schedule'
    | '/admin/teams'
    | '/admin/venues'
    | '/pertandingan/$matchId'
    | '/tim/$teamId'
    | '/admin/'
    | '/match/$matchId/control'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/live'
    | '/masuk'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/admin/contingents'
    | '/admin/groups'
    | '/admin/match-officials'
    | '/admin/matches'
    | '/admin/officials'
    | '/admin/players'
    | '/admin/schedule'
    | '/admin/teams'
    | '/admin/venues'
    | '/pertandingan/$matchId'
    | '/tim/$teamId'
    | '/admin'
    | '/match/$matchId/control'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/live'
    | '/masuk'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/admin/contingents'
    | '/admin/groups'
    | '/admin/match-officials'
    | '/admin/matches'
    | '/admin/officials'
    | '/admin/players'
    | '/admin/schedule'
    | '/admin/teams'
    | '/admin/venues'
    | '/pertandingan/$matchId'
    | '/tim/$teamId'
    | '/admin/'
    | '/match/$matchId/control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HasilRoute: typeof HasilRoute
  JadwalRoute: typeof JadwalRoute
  KlasemenRoute: typeof KlasemenRoute
  LiveRoute: typeof LiveRoute
  MasukRoute: typeof MasukRoute
  PemainRoute: typeof PemainRoute
  PutraRoute: typeof PutraRoute
  PutriRoute: typeof PutriRoute
  TimRoute: typeof TimRouteWithChildren
  TopSkorRoute: typeof TopSkorRoute
  VenueRoute: typeof VenueRoute
  PertandinganMatchIdRoute: typeof PertandinganMatchIdRoute
  MatchMatchIdControlRoute: typeof MatchMatchIdControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasemen': {
      id: '/klasemen'
      path: '/klasemen'
      fullPath: '/klasemen'
      preLoaderRoute: typeof KlasemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemain': {
      id: '/pemain'
      path: '/pemain'
      fullPath: '/pemain'
      preLoaderRoute: typeof PemainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putra': {
      id: '/putra'
      path: '/putra'
      fullPath: '/putra'
      preLoaderRoute: typeof PutraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putri': {
      id: '/putri'
      path: '/putri'
      fullPath: '/putri'
      preLoaderRoute: typeof PutriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-skor': {
      id: '/top-skor'
      path: '/top-skor'
      fullPath: '/top-skor'
      preLoaderRoute: typeof TopSkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contingents': {
      id: '/admin/contingents'
      path: '/contingents'
      fullPath: '/admin/contingents'
      preLoaderRoute: typeof AdminContingentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match-officials': {
      id: '/admin/match-officials'
      path: '/match-officials'
      fullPath: '/admin/match-officials'
      preLoaderRoute: typeof AdminMatchOfficialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officials': {
      id: '/admin/officials'
      path: '/officials'
      fullPath: '/admin/officials'
      preLoaderRoute: typeof AdminOfficialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pertandingan/$matchId': {
      id: '/pertandingan/$matchId'
      path: '/pertandingan/$matchId'
      fullPath: '/pertandingan/$matchId'
      preLoaderRoute: typeof PertandinganMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim/$teamId': {
      id: '/tim/$teamId'
      path: '/$teamId'
      fullPath: '/tim/$teamId'
      preLoaderRoute: typeof TimTeamIdRouteImport
      parentRoute: typeof TimRoute
    }
    '/match/$matchId/control': {
      id: '/match/$matchId/control'
      path: '/match/$matchId/control'
      fullPath: '/match/$matchId/control'
      preLoaderRoute: typeof MatchMatchIdControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContingentsRoute: typeof AdminContingentsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMatchOfficialsRoute: typeof AdminMatchOfficialsRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminOfficialsRoute: typeof AdminOfficialsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContingentsRoute: AdminContingentsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMatchOfficialsRoute: AdminMatchOfficialsRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminOfficialsRoute: AdminOfficialsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TimRouteChildren {
  TimTeamIdRoute: typeof TimTeamIdRoute
}

const TimRouteChildren: TimRouteChildren = {
  TimTeamIdRoute: TimTeamIdRoute,
}

const TimRouteWithChildren = TimRoute._addFileChildren(TimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HasilRoute: HasilRoute,
  JadwalRoute: JadwalRoute,
  KlasemenRoute: KlasemenRoute,
  LiveRoute: LiveRoute,
  MasukRoute: MasukRoute,
  PemainRoute: PemainRoute,
  PutraRoute: PutraRoute,
  PutriRoute: PutriRoute,
  TimRoute: TimRouteWithChildren,
  TopSkorRoute: TopSkorRoute,
  VenueRoute: VenueRoute,
  PertandinganMatchIdRoute: PertandinganMatchIdRoute,
  MatchMatchIdControlRoute: MatchMatchIdControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
