/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KlasemenRouteImport } from './routes/klasemen'
import { Route as PemainRouteImport } from './routes/pemain'
import { Route as PutraRouteImport } from './routes/putra'
import { Route as PutriRouteImport } from './routes/putri'
import { Route as TimRouteImport } from './routes/tim'
import { Route as TopSkorRouteImport } from './routes/top-skor'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as TimTeamIdRouteImport } from './routes/tim.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasemenRoute = KlasemenRouteImport.update({
  id: '/klasemen',
  path: '/klasemen',
  getParentRoute: () => rootRouteImport,
} as any)
const PemainRoute = PemainRouteImport.update({
  id: '/pemain',
  path: '/pemain',
  getParentRoute: () => rootRouteImport,
} as any)
const PutraRoute = PutraRouteImport.update({
  id: '/putra',
  path: '/putra',
  getParentRoute: () => rootRouteImport,
} as any)
const PutriRoute = PutriRouteImport.update({
  id: '/putri',
  path: '/putri',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const TopSkorRoute = TopSkorRouteImport.update({
  id: '/top-skor',
  path: '/top-skor',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const TimTeamIdRoute = TimTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TimRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRoute
  '/putra': typeof PutraRoute
  '/putri': typeof PutriRoute
  '/tim': typeof TimRouteWithChildren
  '/top-skor': typeof TopSkorRoute
  '/venue': typeof VenueRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/tim/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/tim/$teamId'
  id:
    | '__root__'
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/putra'
    | '/putri'
    | '/tim'
    | '/top-skor'
    | '/venue'
    | '/tim/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HasilRoute: typeof HasilRoute
  JadwalRoute: typeof JadwalRoute
  KlasemenRoute: typeof KlasemenRoute
  PemainRoute: typeof PemainRoute
  PutraRoute: typeof PutraRoute
  PutriRoute: typeof PutriRoute
  TimRoute: typeof TimRouteWithChildren
  TopSkorRoute: typeof TopSkorRoute
  VenueRoute: typeof VenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasemen': {
      id: '/klasemen'
      path: '/klasemen'
      fullPath: '/klasemen'
      preLoaderRoute: typeof KlasemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemain': {
      id: '/pemain'
      path: '/pemain'
      fullPath: '/pemain'
      preLoaderRoute: typeof PemainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putra': {
      id: '/putra'
      path: '/putra'
      fullPath: '/putra'
      preLoaderRoute: typeof PutraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putri': {
      id: '/putri'
      path: '/putri'
      fullPath: '/putri'
      preLoaderRoute: typeof PutriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-skor': {
      id: '/top-skor'
      path: '/top-skor'
      fullPath: '/top-skor'
      preLoaderRoute: typeof TopSkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim/$teamId': {
      id: '/tim/$teamId'
      path: '/$teamId'
      fullPath: '/tim/$teamId'
      preLoaderRoute: typeof TimTeamIdRouteImport
      parentRoute: typeof TimRoute
    }
  }
}

interface TimRouteChildren {
  TimTeamIdRoute: typeof TimTeamIdRoute
}

const TimRouteChildren: TimRouteChildren = {
  TimTeamIdRoute: TimTeamIdRoute,
}

const TimRouteWithChildren = TimRoute._addFileChildren(TimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HasilRoute: HasilRoute,
  JadwalRoute: JadwalRoute,
  KlasemenRoute: KlasemenRoute,
  PemainRoute: PemainRoute,
  PutraRoute: PutraRoute,
  PutriRoute: PutriRoute,
  TimRoute: TimRouteWithChildren,
  TopSkorRoute: TopSkorRoute,
  VenueRoute: VenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
